---
- name: "Generate Device Configuration with Data Gathered with GraphQL"
  hosts: all
  gather_facts: false
  connection: local
  vars:
    nautobot_token: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    query_string: |
      query ($device_name: [String!]) {
        devices (name: $device_name) {
          id
          name
          interfaces {
            name
            ip_addresses {
              address
            }
          }
        }
      }

  tasks:
  - name: "Gather Interfaces and IP addresses information per device"
    networktocode.nautobot.query_graphql:
      url: "https://demo.nautobot.com/"
      token: "{{ nautobot_token }}"
      query: "{{ query_string }}"
      graph_variables: "{{ gql_variables }}"
      update_hostvars: yes
    vars:
      gql_variables:
        device_name: "{{ inventory_hostname }}"

  - name: "Generate Configuration"
    ansible.builtin.template:
      src: "config_template.j2"
      dest: "generated_configs/{{ inventory_hostname }}.cfg"
